from os import getenv

DEFAULT_PRICE_VALUE = 0.0
BLUE_DOLLAR_URL = getenv("BLUE_DOLLAR_URL")
OFFICIAL_DOLLAR_URL = getenv("OFFICIAL_DOLLAR_URL")
LEDES_DOLLAR_URL = getenv("LEDES_DOLLAR_URL")
MEP_DOLLAR_URL = getenv("MEP_DOLLAR_URL")
