# Generated by Django 4.0.7 on 2024-03-01 17:47

import core.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolar',
            name='type_of_quote',
            field=django_enumfield.db.fields.EnumField(enum=core.enums.DolarType, help_text='Type of quote'),
        ),
    ]
