# Generated by Django 4.2.10 on 2024-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dollar",
            name="extra_data",
            field=models.JSONField(default=dict, help_text="Extra data for the dollar"),
        ),
    ]
