name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        directory: .env/
        file_name: .dev-sample
        fail_on_empty: false
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
