name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-env-file:
    uses: SpicyPizza/create-envfile@v2.0.3
    with:
      file_name: .dev-sample
      directory:  ${{ github.workspace }}/dolariz_ar/.env/.dev-sample
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
