# Help me to build the images and push the web to the github container registry

name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create .env file
        # You may pin to the exact commit or the version.
        # uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          file_name: .dev-sample
          directory: ./.env/

      - name: Docker compose build
        run: docker-compose -f ./dolariz_ar/docker-compose.yml build
      
      - name: Push the django image
        run: docker-compose -f ./dolariz_ar/docker-compose.yml push web
