name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-env-file:
    runs-on: ubuntu-latest

    steps:
    - uses: DeveloperRic/action-create-env@v1.0.2 # set this to the version of your choice
    - with:
        # Write your content here if you want. The content will be trimmed & dedent will be applied.
        full_text: |
          DEBUG=1
          SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
          DJANGO_ALLOWED_HOSTS=*
          
          SQL_ENGINE=django.db.backends.postgresql
          SQL_DATABASE=hello_django
          SQL_USER=hello_django
          SQL_PASSWORD=hello_django
          SQL_HOST=db
          SQL_PORT=5432
          
          CELERY_BROKER_URL=redis://redis:6379/0
          CELERY_RESULT_BACKEND=redis://redis:6379/0
          CELERY_BROKER=redis://redis:6379/0
          CELERY_BACKEND=redis://redis:6379/0
          DJANGO_SUPERUSER_PASSWORD=mdr.1234
          DEFAULT_ADMIN_PASSWORD=mdr.1234
          DEFAULT_ADMIN_EMAIL=matias-dr@outlook.com
          DEFAULT_ADMIN_USERNAME=mdr
          
          BLUE_DOLLAR_URL=https://dolarhoy.com/
          OFFICIAL_DOLLAR_URL=https://www.bna.com.ar/Personas
        directory: ${{ github.workspace }}/dolariz_ar/.env/.dev-sample

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
