name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: ".env/.dev-sample"
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
